baseurl = "http://www.alexsolab.com"
languageCode = "en-us"
title = "Alejandro Sola Banasco"
theme = "retrofulhugo"
pygmentsUseClasses = true
googleAnalytics = "UA-114459551-1"
#disqusShortname = "XXX"

[Params]
  subtitle = "Or yond dark lodging wh're the thoughts dwelleth..."
  logo = "img/logo.png"
  favicon = "img/favicon.ico"
  commit = false

[Author]
  handle = "AlexSola"
  name = "Alejandro Sola Banasco"
  email = "alejandro.sola.banasco@gmail.com"
  github = "alexsola"
  twitter = "asolabanasco"
  youtube = "channel/UCiQVbLN-Ct9CKNA0cGeVZJg"
  linkedin = "in/alejandro-sola-a2855315"
  soundcloud = "alejandro-sola-banasco"

[[menu.main]]
    name = "Introduction"
    url = "/page/introduction/"
    weight = 1

[[menu.main]]
    name = "CV"
    url = "/page/cv/"
    weight = 2 
